# Generated by Django 5.2.3 on 2025-06-17 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo', max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Campaña',
                'verbose_name_plural': 'Campañas',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo', max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del cliente', max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(help_text='Apellido del cliente', max_length=50, verbose_name='Apellido')),
                ('direccion_postal', models.CharField(blank=True, help_text='Dirección postal del cliente', max_length=100, null=True, verbose_name='Dirección Postal')),
                ('numero_telefono', models.CharField(blank=True, help_text='Número de teléfono del cliente', max_length=30, null=True, verbose_name='Número de Teléfono')),
                ('correo', models.EmailField(blank=True, help_text='Correo electrónico del cliente', max_length=100, null=True, verbose_name='Correo Electrónico')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PaginaWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='URL de la página web', verbose_name='URL')),
                ('nombre', models.CharField(help_text='Nombre de la página web', max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Página Web',
                'verbose_name_plural': 'Páginas Web',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoAnuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo', max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Tipo de Anuncio',
                'verbose_name_plural': 'Tipos de Anuncios',
            },
        ),
        migrations.CreateModel(
            name='TopicoPagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo', max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Tópico de Página',
                'verbose_name_plural': 'Tópicos de Páginas',
            },
        ),
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del anuncio', max_length=100, verbose_name='Nombre')),
                ('titulo', models.CharField(help_text='Título del anuncio', max_length=100, verbose_name='Título')),
                ('contenido', models.TextField(help_text='Contenido del anuncio', verbose_name='Contenido')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio del anuncio', max_digits=10, verbose_name='Precio')),
                ('campania', models.ForeignKey(help_text='Campaña a la que pertenece el anuncio', on_delete=django.db.models.deletion.PROTECT, related_name='anuncios', to='agencia.campania', verbose_name='Campaña')),
                ('categoria', models.ForeignKey(blank=True, help_text='Categoría del anuncio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anuncios', to='agencia.categoria', verbose_name='Categoría')),
                ('tipo', models.ForeignKey(blank=True, help_text='Tipo de anuncio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anuncios', to='agencia.tipoanuncio', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Anuncio',
                'verbose_name_plural': 'Anuncios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ContratacionAnuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_contratacion', models.DateTimeField(help_text='Fecha y hora de contratación del anuncio', verbose_name='Fecha de Contratación')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio de la contratación', max_digits=10, verbose_name='Precio')),
                ('anuncio', models.ForeignKey(help_text='Anuncio contratado', on_delete=django.db.models.deletion.PROTECT, related_name='contrataciones', to='agencia.anuncio', verbose_name='Anuncio')),
                ('cliente', models.ForeignKey(help_text='Cliente que contrata el anuncio', on_delete=django.db.models.deletion.PROTECT, related_name='contrataciones', to='agencia.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Contratación de Anuncio',
                'verbose_name_plural': 'Contrataciones de Anuncios',
                'ordering': ['-fecha_contratacion'],
            },
        ),
        migrations.CreateModel(
            name='AparicionAnuncioPagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio_aparicion', models.DateTimeField(help_text='Fecha y hora de inicio de aparición', verbose_name='Fecha de Inicio')),
                ('fecha_fin_aparicion', models.DateTimeField(blank=True, help_text='Fecha y hora de fin de aparición', null=True, verbose_name='Fecha de Fin')),
                ('anuncio', models.ForeignKey(help_text='Anuncio que aparece en la página', on_delete=django.db.models.deletion.PROTECT, related_name='apariciones', to='agencia.anuncio', verbose_name='Anuncio')),
                ('pagina_web', models.ForeignKey(help_text='Página web donde aparece el anuncio', on_delete=django.db.models.deletion.PROTECT, related_name='apariciones', to='agencia.paginaweb', verbose_name='Página Web')),
            ],
            options={
                'verbose_name': 'Aparición de Anuncio en Página',
                'verbose_name_plural': 'Apariciones de Anuncios en Páginas',
                'ordering': ['-fecha_inicio_aparicion'],
            },
        ),
        migrations.AddField(
            model_name='paginaweb',
            name='topico',
            field=models.ForeignKey(blank=True, help_text='Tópico de la página web', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paginas', to='agencia.topicopagina', verbose_name='Tópico'),
        ),
    ]
