# Generated by Django 5.2.3 on 2025-06-17 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='ingrediente',
            field=models.ForeignKey(help_text='Ingrediente de la receta', on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='pastas.ingrediente'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='producto',
            field=models.ForeignKey(help_text='Producto de la receta', on_delete=django.db.models.deletion.PROTECT, related_name='ingredientes', to='pastas.producto'),
        ),
    ]
